Traceback (most recent call last):
  File "/home/mmadeira/anaconda3/envs/IPC-2020-21/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/home/mmadeira/anaconda3/envs/IPC-2020-21/lib/python3.7/site-packages/nbclient/client.py", line 1077, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/mmadeira/anaconda3/envs/IPC-2020-21/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/mmadeira/anaconda3/envs/IPC-2020-21/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/mmadeira/anaconda3/envs/IPC-2020-21/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/mmadeira/anaconda3/envs/IPC-2020-21/lib/python3.7/site-packages/nbclient/client.py", line 527, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/home/mmadeira/anaconda3/envs/IPC-2020-21/lib/python3.7/site-packages/nbclient/client.py", line 822, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/mmadeira/anaconda3/envs/IPC-2020-21/lib/python3.7/site-packages/nbclient/client.py", line 730, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
print (primos_ate_10)

print (primos_ate_10[0]) # Note que o primeiro elemento est√° na posi√ß√£o 0  
print (primos_ate_10[4]) # o √∫ltimo est√° na posi√ß√£o 4
print (primos_ate_10[-1]) # ou seja, na primeira posi√ß√£o a contar do fim
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-28-d348f4676441>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mprint[0m [0;34m([0m[0mprimos_ate_10[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;34m[0m[0m
[1;32m      3[0m [0mprint[0m [0;34m([0m[0mprimos_ate_10[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m)[0m [0;31m# Note que o primeiro elemento est√° na posi√ß√£o 0[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mprint[0m [0;34m([0m[0mprimos_ate_10[0m[0;34m[[0m[0;36m4[0m[0;34m][0m[0;34m)[0m [0;31m# o √∫ltimo est√° na posi√ß√£o 4[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mprint[0m [0;34m([0m[0mprimos_ate_10[0m[0;34m[[0m[0;34m-[0m[0;36m1[0m[0;34m][0m[0;34m)[0m [0;31m# ou seja, na primeira posi√ß√£o a contar do fim[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'primos_ate_10' is not defined
NameError: name 'primos_ate_10' is not defined

